### PR TITLE
You guys didnt test this did you...

### PR DESCRIPTION
**Pull request by MrEnxo**
making it return undefined makes shit not work

### CODE REVIEW

**Comment by MrEnxo** [comment]
most helpful pull request 2022

**Comment by tacheometry** [comment]
You didn't test this, did you? roblox-ts doesn't allow `null`.

**Comment by MrEnxo** [comment]
i mean i did and it works pretty good for my uis

**Comment by MrEnxo** [comment]
Yea Typescript is being Jank with JSX and making it want Element | null types idk whats causing this but this does seem to fix it on my local project

**Comment by Rimuy** [comment]
Haha.

**Pull request closed without merging**
